os: ubuntu
dist: bionic
#sudo: required  # gives more RAM (otherwise memory error for TOM)
language: python
services:
  - docker
jobs:
  include:
  - python: "3.6"
    env:
      - PYTORCH_URL="torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html"
      - PYTHON_VERS=3.6
    script: ./travis_test
  - python: "3.7"
    env:
      - PYTORCH_URL="torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html"
      - PYTHON_VERS=3.7
    script: ./travis_test
  - python: "3.8"
    env:
      - PYTORCH_URL="torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html"
      - PYTHON_VERS=3.8
    script: ./travis_test
  - stage: Deploy to Dockerhub
    python: "3.7"
    env:
      - PYTORCH_URL="torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html"
      - PYTHON_VERS=3.7
    script: ./travis_docker
before_install:
  - pip install $PYTORCH_URL
install:
  - pip install .



