dist: trusty
sudo: required  # gives more RAM (otherwise memory error for TOM)
language: python
#services:
#  - docker
matrix:
  include:
  - python: "2.7"
    env: PYTORCH_URL=http://download.pytorch.org/whl/cpu/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl
  - python: "3.5"
    env: PYTORCH_URL=http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl
before_install:
  - pip install $PYTORCH_URL
  - pip install https://github.com/MIC-DKFZ/batchgenerators/archive/master.zip
install:
  - pip install .
script:
#  - docker build -t tractseg_container .
#  - docker run -v $TRAVIS_BUILD_DIR/examples:/data -it tractseg_container TractSeg -i /data/Diffusion.nii.gz -o /data
#  - docker run -v $TRAVIS_BUILD_DIR/examples:/data -it wasserth/tractseg_container:v1.4 TractSeg -i /data/Diffusion.nii.gz -o /data
  - TractSeg -i examples/Diffusion_mrtrix_peaks.nii.gz --skip_peak_extraction --single_orientation --single_output_file
#  - TractSeg -i examples/Diffusion_mrtrix_peaks.nii.gz --skip_peak_extraction --output_type TOM --single_orientation --single_output_file
  - TractSeg -i examples/Diffusion_mrtrix_peaks.nii.gz --skip_peak_extraction --output_type endings_segmentation --single_orientation --single_output_file
  - pytest